package game

// ReserveSpecies lists the species of each reserve, by reserve number (the game has no such table).
var ReserveSpecies = map[int][]string{
	0:  {"canadagoose", "pheasant", "europeanrabbit", "redfox", "roedeer", "fallowdeer", "wildboar", "reddeer", "europeanbison"},                                                                                                                                                                                 // Hirschfelden
	1:  {"mallard", "wildturkey", "jackrabbit", "coyote", "blacktaildeer", "whitetaildeer", "blackbear", "rooseveltelk", "moose"},                                                                                                                                                                                // Layton Lake
	2:  {"westerncapercaillie", "muskdeer", "eurasianlynx", "wildboar", "graywolf", "reindeer", "brownbear", "moose"},                                                                                                                                                                                            // Medved-Taiga
	3:  {"eurasianwigeon", "scrubhare", "sidestripedjackal", "springbok", "lesserkudu", "warthog", "gemsbok", "bluewildebeest", "capebuffalo", "lion"},                                                                                                                                                           // Vurhonga Savanna
	4:  {"cinnamonteal", "blackbuck", "axisdeer", "collaredpeccary", "muledeer", "puma", "reddeer", "waterbuffalo"},                                                                                                                                                                                              // Parque Fernando
	6:  {"canadagoose", "harlequinduck", "redfox", "caribou", "graywolf", "moose", "grizzlybear", "plainsbison"},                                                                                                                                                                                                 // Yukon Valley
	8:  {"pheasant", "europeanhare", "roedeer", "beceiteibex", "southeasternibex", "gredosibex", "rondaibex", "iberianmouflon", "wildboar", "reddeer", "iberianwolf"},                                                                                                                                            // Cuatro Colinas
	9:  {"wildturkey", "pronghorn", "mountaingoat", "muledeer", "bighornsheep", "puma", "blackbear", "rockymountainelk", "plainsbison"},                                                                                                                                                                          // Silver Ridge Peaks
	10: {"mallard", "wildturkey", "europeanrabbit", "chamois", "feralgoat", "sikadeer", "fallowdeer", "tahr", "feralpig", "reddeer", "moose"},                                                                                                                                                                    // Te Awaroa
	11: {"riograndeturkey", "pheasant", "antelopejackrabbit", "coyote", "mexicanbobcat", "pronghorn", "collaredpeccary", "whitetaildeer", "muledeer", "desertbighornsheep"},                                                                                                                                      // Rancho del Arroyo
	12: {"northernbobwhitequail", "easternwildturkey", "easterncottontailrabbit", "greenwingteal", "raccoon", "grayfox", "whitetaildeer", "feralpig", "americanalligator", "blackbear"},                                                                                                                          // Mississippi Acres
	13: {"canadagoose", "eurasianwigeon", "mallard", "tuftedduck", "goldeneye", "hazelgrouse", "westerncapercaillie", "rockptarmigan", "willowptarmigan", "mountainhare", "greylaggoose", "tundrabeangoose", "eurasianteal", "blackgrouse", "raccoondog", "eurasianlynx", "whitetaildeer", "brownbear", "moose"}, // Revontuli Coast
	14: {"northernbobwhitequail", "mallard", "easternwildturkey", "pheasant", "goldeneye", "easterncottontailrabbit", "greenwingteal", "coyote", "bobcat", "raccoon", "grayfox", "redfox", "whitetaildeer", "blackbear", "moose"},                                                                                // New England
	16: {"stubblequail", "magpiegoose", "redfox", "axisdeer", "hogdeer", "feralgoat", "fallowdeer", "easterngreykangaroo", "javanrusa", "feralpig", "reddeer", "sambar", "saltwatercrocodile", "banteng"},                                                                                                        // Emerald Coast
	17: {"woollyhare", "greylaggoose", "northernredmuntjac", "tibetanfox", "blackbuck", "bluesheep", "tahr", "snowleopard", "nilgai", "barasingha", "waterbuffalo", "bengaltiger", "wildyak"},                                                                                                                    // Sundarpatan (Népal)
	18: {"gadwall", "eurasianwigeon", "mallard", "pheasant", "tuftedduck", "ferruginousduck", "goldeneye", "europeanrabbit", "greylaggoose", "tundrabeangoose", "eurasianteal", "blackgrouse", "raccoondog", "raccoon", "redfox"},                                                                                // Salzwiesen Park
	19: {"canadagoose", "woodduck", "northernpintail", "mallard", "pheasant", "snowgoose", "duskygrouse", "northamericanbeaver", "pronghorn", "whitetaildeer", "mountaingoat", "muledeer", "bighornsheep", "woodlandcaribou", "graywolf", "blackbear", "manitobanelk", "moose", "woodbison"},                     // Askiy Ridge
	20: {"eurasianwoodcock", "eurasianwigeon", "pheasant", "westerncapercaillie", "redgrouse", "mountainhare", "eurasianpinemarten", "blackgrouse", "americanmink", "europeanbadger", "redfox", "feralgoat", "roedeer", "sikadeer", "fallowdeer", "wildboar", "reddeer"},                                         // Tòrr nan Sithean
	21: {"westernmountaincoati", "greatergrison", "cinnamonteal", "ocelot", "collaredpeccary", "taruca", "vicuna", "capybara", "whitetaildeer", "puma", "jaguar", "spectacledbear", "southamericantapir", "blackcaiman"},                                                                                         // Intisuyu (Pérou)
}
