package main

import (
	"strings"

	"github.com/Laink/COTWGoldChallenge/internal/patch"
)

// UI holds the program messages in one language.
type UI struct{ m map[string]string }

func (u UI) t(k string) string {
	if s, ok := u.m[k]; ok {
		return s
	}
	return messages["en"][k]
}

func uiFor(steamLanguage string) UI {
	if patch.LanguageFor(steamLanguage) == "fr" {
		return UI{messages["fr"]}
	}
	return UI{messages["en"]}
}

var messages = map[string]map[string]string{
	"en": {
		"credit":            "designed by Laink",
		"not_found":         "theHunter: Call of the Wild was not found.",
		"ask_folder":        "Game folder (theHunterCotW), or Enter to quit: ",
		"not_game":          "This folder does not contain the game.",
		"game":              "Game:    ",
		"language":          "Language:",
		"preamble":          "The medal gauge needs the \"Spotting Knowledge\" skill, level 3: the mod reads the trophy estimate this skill gives through binoculars. Without it, the gauge shows the medal thresholds of the species but not where the animal stands.",
		"menu":              "  2  Uninstall\n  3  Settings and trophies (page in your browser)",
		"menu_install":      "  1  Install / update",
		"menu_update":       "UPDATE REQUIRED",
		"menu_key_off":      "  4  Overlay keys: OFF (type 4 to turn them on)",
		"menu_key_on":       "  4  Overlay keys: ON, %s (type 4 to turn them off)",
		"menu_key_nokey":    "  4  Overlay keys: ON, but no key is chosen, set them in 3 (type 4 to turn them off)",
		"menu_quit":         "     Enter to quit (stops recording your harvests)",
		"menu_quit_on":      "     Enter to quit (stops recording your harvests and the overlay keys)",
		"title_open":        "keep this window open while you play",
		"banner":            "KEEP THIS WINDOW OPEN WHILE YOU PLAY. It records your harvests (the game keeps only part of them) and runs the overlay keys. You can minimize it.",
		"banner_count":      "Harvests recorded: %d",
		"banner_manual":     ", trophies added by hand: %d",
		"banner_release":    "NEW VERSION %s AVAILABLE: download it here:",
		"choice":            "\nType your choice (1 to 4): ",
		"wait_enter":        "Press Enter here to stop.",
		"date_format":       "2006-01-02",
		"state_none":        "The mod is not installed: choose 1.",
		"state_installed":   "The mod is installed (%s, version %s).",
		"state_program":     "This program is a different version: choose 1 to update the mod.",
		"state_game":        "The game was updated since: choose 1 to install the mod again.",
		"state_legacy":      "The former version (COTWSpottingPlus) is installed: choose 1 to switch to COTWGoldChallenge.",
		"key_on":            "Overlay keys on: %s. Keep this window open while you play.",
		"key_nokey":         "Overlay keys on, but no key is chosen: choose them in the settings (3).",
		"key_off":           "Overlay keys off.",
		"keys_toggle":       "%s shows or hides the overlay",
		"keys_names":        "%s held shows the names of the missing species",
		"keys_opaque":       "%s held shows the species outside the reserve at full opacity",
		"shortcut_windows":  "the shortcut only works on Windows",
		"confirm":           "Continue? (y/n) ",
		"no_hud":            "ui/clue_hud.gfx was not found in the game archives.",
		"reading":           "Reading the trophy data of the game...",
		"step_types":        "species",
		"step_antlers":      "antlers and horns",
		"species":           "%d species.",
		"patch_failed":      "this game version is not supported",
		"other_mod":         "Another mod already replaces %s. Its files will be kept as .bak and come back if you uninstall.",
		"no_saves":          "Your save folder was not found: play the game once, then run COTWGoldChallenge again, for the overlay to see your harvests.",
		"no_link":           "The link to your save folder could not be made:",
		"installed":         "Installed.",
		"launch_ok":         "The Steam launch options already load mods.",
		"restart":           "Restart the game to see the mod.",
		"first_run":         "First installation: the settings (choice 3) are in the menu below, and every time you run COTWGoldChallenge. The overlay keys start with the program.",
		"launch_todo":       "In Steam: right-click the game > Properties > Launch options, and paste:",
		"launch_ok_epic":    "The Epic Games Launcher already loads mods.",
		"whole_line":        "Copy the whole line, with the final dot: it is part of the options.",
		"saves_linked":      "Your save folder is now linked: the overlay sees your harvests.",
		"several":           "The game is installed several times:",
		"choice_game":       "Which one? (Enter for 1): ",
		"launch_todo_epic":  "In the Epic Games Launcher: Library > \"...\" on theHunter: Call of the Wild > Manage > Launch options (on older launchers: Settings > Manage games > the game > Additional command line arguments), and paste:",
		"copied":            "(copied to the clipboard)",
		"not_installed":     "COTWGoldChallenge is not installed.",
		"removed":           "Removed.",
		"error":             "Error:",
		"denied":            "access denied to the game folder. Run COTWGoldChallenge as administrator.",
		"settings_open":     "The settings and trophies page is open in your browser:",
		"page_title":        "Settings",
		"page_intro":        "Your changes are saved as you make them and show in the game within a few seconds, even while you play. The binocular gauge needs the Spotting Knowledge skill, level 3.",
		"page_reset_ask":    "Set every setting back to its default value?",
		"page_saved":        "Saved. The game applies it within a few seconds.",
		"page_reset":        "Default values",
		"page_close":        "Close",
		"page_closed":       "You can close this tab.",
		"page_advanced":     "Advanced settings",
		"page_always":       "All time",
		"page_preview":      "Preview",
		"page_preview_note": "Approximate layout. In the game, each hexagon is the species icon.",
		"page_time":         "time (optional)",
		"page_zoom":         "Overlay",
		"page_panels":       "Binoculars and call panels",
		"page_zone_note":    "The overlay is moved out of the top right corner, where the game shows its panels.",
		"page_key_set":      "Change",
		"page_key_clear":    "None",
		"page_key_wait":     "Press a key or a mouse button (Esc to cancel)",
		"page_key_none":     "No key",
		"page_mouse":        "Mouse",
		"page_list_note":    "The list only shows in reserve mode, or in 100% mode when \"show every species\" is off.",
		"page_full":         "Screen",
		"page_tab_settings": "Settings",
		"page_tab_trophies": "Trophies",
		"page_trophies":     "Trophies by reserve",
		"page_troph_intro":  "The game keeps only the 5 best harvests of each species and the last 20: older trophies can be missing from the overlay. Add them here: each choice is saved as soon as you click it. A trophy added by hand counts in the challenge shown (start date and mode of the Settings tab), and shows in the game within a few seconds.",
		"page_keep_open":    "Keep COTWGoldChallenge open while you play: it records every harvest, so that none is lost again.",
		"page_reserve":      "Reserve",
		"page_detected":     "Found in your harvests",
		"page_by_hand":      "Added by hand",
		"page_recorded":     "Harvests recorded: %d. Trophies added by hand: %d.",
		"page_no_mod":       "Install the mod first (choice 1).",
		"page_great_one":    "Great One",
		"page_rank_none":    "None",
		"page_mode_mega":    "100% mode: the harvests of every reserve count.",
		"page_mode_reserve": "Reserve mode: only the harvests of this reserve count.",
		"page_tab_stats":    "Stats",
		"page_overview":     "Overview",
		"page_by_species":   "Species of the reserve",
		"page_all_species":  "All species",
		"page_missing":      "Missing species, all reserves (%d): where to hunt them",
		"page_missing_none": "None: every species is done.",
		"page_stats_note":   "Harvests recorded by COTWGoldChallenge, trophies added by hand left out. Before it recorded them, the game kept only part of your harvests.",
		"page_stats_since":  "Since the challenge start",
		"page_stats_all":    "Whole history",
		"page_harvests":     "Harvests",
		"page_species_n":    "Different species",
		"page_medals":       "Medals",
		"page_by_reserve":   "By reserve",
		"page_top_species":  "Most harvested species",
		"page_recent":       "Last harvests",
		"page_col_date":     "Date",
		"page_col_species":  "Species",
		"page_col_score":    "Score",
		"page_col_medal":    "Medal",
		"page_unknown":      "Unknown reserve",
		"page_no_harvest":   "No harvest recorded for this period.",
		"press_enter":       "Press Enter to close.",
	},
	"fr": {
		"credit":            "conçu par Laink",
		"not_found":         "theHunter: Call of the Wild est introuvable.",
		"ask_folder":        "Dossier du jeu (theHunterCotW), ou Entrée pour quitter : ",
		"not_game":          "Ce dossier ne contient pas le jeu.",
		"game":              "Jeu :    ",
		"language":          "Langue :",
		"preamble":          "La jauge de médaille nécessite la compétence \"Connaissance du repérage\" niveau 3 : le mod lit l'estimation de trophée que donne cette compétence aux jumelles. Sans elle, la jauge affiche les seuils de médaille de l'espèce, mais pas où se situe l'animal.",
		"menu":              "  2  Désinstaller\n  3  Réglages et trophées (page dans votre navigateur)",
		"menu_install":      "  1  Installer / mettre à jour",
		"menu_update":       "MISE À JOUR REQUISE",
		"menu_key_off":      "  4  Touches de l'overlay : DÉSACTIVÉES (tapez 4 pour les activer)",
		"menu_key_on":       "  4  Touches de l'overlay : ACTIVÉES, %s (tapez 4 pour les désactiver)",
		"menu_key_nokey":    "  4  Touches de l'overlay : ACTIVÉES, mais aucune touche choisie, réglez-les en 3 (tapez 4 pour les désactiver)",
		"menu_quit":         "     Entrée pour quitter (arrête l'enregistrement de vos prélèvements)",
		"menu_quit_on":      "     Entrée pour quitter (arrête l'enregistrement de vos prélèvements et les touches de l'overlay)",
		"title_open":        "laissez cette fenêtre ouverte pendant que vous jouez",
		"banner":            "LAISSEZ CETTE FENÊTRE OUVERTE PENDANT QUE VOUS JOUEZ. Elle enregistre vos prélèvements (le jeu n'en garde qu'une partie) et fait fonctionner les touches de l'overlay. Vous pouvez la réduire.",
		"banner_count":      "Prélèvements enregistrés : %d",
		"banner_manual":     ", trophées saisis à la main : %d",
		"banner_release":    "NOUVELLE VERSION %s DISPONIBLE : téléchargez-la ici :",
		"choice":            "\nTapez votre choix (1 à 4) : ",
		"wait_enter":        "Appuyez sur Entrée ici pour arrêter.",
		"date_format":       "02/01/2006",
		"state_none":        "Le mod n'est pas installé : choisissez 1.",
		"state_installed":   "Le mod est installé (le %s, version %s).",
		"state_program":     "Ce programme est une autre version : choisissez 1 pour mettre à jour le mod.",
		"state_game":        "Le jeu a été mis à jour depuis : choisissez 1 pour réinstaller le mod.",
		"state_legacy":      "L'ancienne version (COTWSpottingPlus) est installée : choisissez 1 pour passer à COTWGoldChallenge.",
		"key_on":            "Touches de l'overlay activées : %s. Laissez cette fenêtre ouverte pendant que vous jouez.",
		"key_nokey":         "Touches de l'overlay activées, mais aucune touche n'est choisie : choisissez-les dans les réglages (3).",
		"key_off":           "Touches de l'overlay désactivées.",
		"keys_toggle":       "%s affiche ou masque l'overlay",
		"keys_names":        "%s maintenue affiche les noms des espèces manquantes",
		"keys_opaque":       "%s maintenue affiche les espèces hors réserve à 100 %% d'opacité",
		"shortcut_windows":  "le raccourci ne fonctionne que sous Windows",
		"confirm":           "Continuer ? (o/n) ",
		"no_hud":            "ui/clue_hud.gfx est introuvable dans les archives du jeu.",
		"reading":           "Lecture des données de trophées du jeu...",
		"step_types":        "espèces",
		"step_antlers":      "bois et cornes",
		"species":           "%d espèces.",
		"patch_failed":      "cette version du jeu n'est pas prise en charge",
		"other_mod":         "Un autre mod remplace déjà %s. Ses fichiers seront conservés en .bak et reviendront si vous désinstallez.",
		"no_saves":          "Votre dossier de sauvegarde est introuvable : lancez une partie une fois, puis relancez COTWGoldChallenge, pour que l'overlay voie vos prises.",
		"no_link":           "Le lien vers votre dossier de sauvegarde n'a pas pu être créé :",
		"installed":         "Installé.",
		"launch_ok":         "Les options de lancement Steam chargent déjà les mods.",
		"restart":           "Relancez le jeu pour voir le mod.",
		"first_run":         "Première installation : les réglages (choix 3) sont dans le menu ci-dessous, et à chaque lancement de COTWGoldChallenge. Les touches de l'overlay démarrent avec le programme.",
		"launch_todo":       "Dans Steam : clic droit sur le jeu > Propriétés > Options de lancement, et collez :",
		"launch_ok_epic":    "Le lanceur Epic Games charge déjà les mods.",
		"whole_line":        "Copiez la ligne entière, point final compris : il fait partie des options.",
		"saves_linked":      "Votre dossier de sauvegarde est maintenant relié : l'overlay voit vos prises.",
		"several":           "Le jeu est installé plusieurs fois :",
		"choice_game":       "Lequel ? (Entrée pour 1) : ",
		"launch_todo_epic":  "Dans le lanceur Epic Games : Bibliothèque > « ... » sur theHunter: Call of the Wild > Gérer > Options de lancement (anciens lanceurs : Paramètres > Gérer les jeux > le jeu > Arguments de ligne de commande supplémentaires), et collez :",
		"copied":            "(copié dans le presse-papiers)",
		"not_installed":     "COTWGoldChallenge n'est pas installé.",
		"removed":           "Désinstallé.",
		"error":             "Erreur :",
		"denied":            "accès refusé au dossier du jeu. Lancez COTWGoldChallenge en tant qu'administrateur.",
		"settings_open":     "La page des réglages et trophées est ouverte dans votre navigateur :",
		"page_title":        "Réglages",
		"page_intro":        "Vos modifications sont enregistrées au fur et à mesure et s'appliquent en jeu en quelques secondes, même en pleine partie. La jauge des jumelles nécessite la compétence « Connaissance du repérage » niveau 3.",
		"page_reset_ask":    "Remettre tous les réglages à leur valeur par défaut ?",
		"page_saved":        "Enregistré. Le jeu l'applique en quelques secondes.",
		"page_reset":        "Valeurs par défaut",
		"page_close":        "Fermer",
		"page_closed":       "Vous pouvez fermer cet onglet.",
		"page_advanced":     "Réglages avancés",
		"page_always":       "Depuis toujours",
		"page_preview":      "Aperçu",
		"page_preview_note": "Disposition approximative. Dans le jeu, chaque hexagone est l'icône de l'espèce.",
		"page_time":         "heure (facultatif)",
		"page_zoom":         "Overlay",
		"page_panels":       "Cadres jumelles et cris",
		"page_zone_note":    "L'overlay est décalé hors du coin en haut à droite, réservé aux cadres du jeu.",
		"page_key_set":      "Changer",
		"page_key_clear":    "Aucune",
		"page_key_wait":     "Appuyez sur une touche ou un bouton de souris (Échap pour annuler)",
		"page_key_none":     "Aucune touche",
		"page_mouse":        "Souris",
		"page_list_note":    "La liste ne s'affiche qu'en mode réserve, ou en mode 100% si « afficher toutes les espèces » est désactivé.",
		"page_full":         "Écran",
		"page_tab_settings": "Réglages",
		"page_tab_trophies": "Trophées",
		"page_trophies":     "Trophées par réserve",
		"page_troph_intro":  "Le jeu ne garde que les 5 meilleurs prélèvements de chaque espèce et les 20 derniers : des trophées anciens peuvent manquer à l'overlay. Ajoutez-les ici : chaque choix est enregistré dès que vous cliquez. Un trophée saisi à la main compte dans le défi affiché (date de début et mode de l'onglet Réglages) et apparaît en jeu en quelques secondes.",
		"page_keep_open":    "Laissez COTWGoldChallenge ouvert pendant que vous jouez : il enregistre chaque prélèvement, pour qu'aucun ne soit plus perdu.",
		"page_reserve":      "Réserve",
		"page_detected":     "Trouvé dans vos prélèvements",
		"page_by_hand":      "Saisi à la main",
		"page_recorded":     "Prélèvements enregistrés : %d. Trophées saisis à la main : %d.",
		"page_no_mod":       "Installez d'abord le mod (choix 1).",
		"page_great_one":    "Great One",
		"page_rank_none":    "Rien",
		"page_mode_mega":    "Mode 100% : les prélèvements de toutes les réserves comptent.",
		"page_mode_reserve": "Mode réserve : seuls les prélèvements de cette réserve comptent.",
		"page_tab_stats":    "Statistiques",
		"page_overview":     "Vue d'ensemble",
		"page_by_species":   "Espèces de la réserve",
		"page_all_species":  "Toutes les espèces",
		"page_missing":      "Espèces manquantes, toutes réserves confondues (%d) : où les chasser",
		"page_missing_none": "Aucune : toutes les espèces sont faites.",
		"page_stats_note":   "Prélèvements enregistrés par COTWGoldChallenge, sans les trophées saisis à la main. Avant qu'il les enregistre, le jeu n'en gardait qu'une partie.",
		"page_stats_since":  "Depuis le début du défi",
		"page_stats_all":    "Tout l'historique",
		"page_harvests":     "Prélèvements",
		"page_species_n":    "Espèces différentes",
		"page_medals":       "Médailles",
		"page_by_reserve":   "Par réserve",
		"page_top_species":  "Espèces les plus prélevées",
		"page_recent":       "Derniers prélèvements",
		"page_col_date":     "Date",
		"page_col_species":  "Espèce",
		"page_col_score":    "Score",
		"page_col_medal":    "Médaille",
		"page_unknown":      "Réserve inconnue",
		"page_no_harvest":   "Aucun prélèvement enregistré sur cette période.",
		"press_enter":       "Appuyez sur Entrée pour fermer.",
	},
}

// wrap breaks a paragraph into lines of at most n characters.
func wrap(s string, n int) string {
	var b strings.Builder
	line := 0
	for i, w := range strings.Fields(s) {
		l := len([]rune(w))
		if i > 0 {
			if line+1+l > n {
				b.WriteString("\n")
				line = 0
			} else {
				b.WriteString(" ")
				line++
			}
		}
		b.WriteString(w)
		line += l
	}
	return b.String()
}
